name: Explore California

on:
  push:
    branches: [main]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup nodejs environment
        uses: actions/setup-node@v3.5.1
      
      - name: configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: install dependencies
        run: npm install
        working-directory: pulumi

      - name: provision aws resources
        id: pulumi
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev # When using an individual account, only use stack-name.
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: upload content to S3
        run: aws s3 sync ./www/ "s3://${{ steps.pulumi.outputs.bucketName }}"



    
      
